"""
backend/app/services/report_generator.py
-----------------------------------------
Corporate recruitment PDF report generation engine using ReportLab.
Produces a structured, executive-grade candidate assessment dossier
with KPI summaries, candidate ranking matrix, rubric fit scores,
structured interview guides, salary benchmarks, and AI governance audit notes.
"""

import io
import re
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
    HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute total pages and stamp running
    headers, footers, and page numbers ("Page X of Y") cleanly on all pages.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(36, 762, "RecruitAI | Executive Candidate Assessment Dossier")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(36, 756, 576, 756)

        # Running footer (all pages)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 38, 576, 38)

        self.drawString(36, 26, "Confidential — Generated by RecruitAI Multi-Agent Recruiting Platform")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(576, 26, page_text)

        self.restoreState()


def markdown_to_html(text: str) -> str:
    """
    Translates markdown bold, code, bullets, and linebreaks into
    ReportLab-compatible XML-safe inline HTML tags.
    """
    if not text:
        return ""

    # 1. Escape XML characters
    escaped = (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    # 2. Markdown bold **bold** -> <b>bold</b>
    escaped = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", escaped)

    # 3. Inline code `code` -> Courier font
    escaped = re.sub(
        r"`(.*?)`",
        r"<font face='Courier' color='#059669'>\1</font>",
        escaped,
    )

    # 4. Markdown headers ### -> <b>...</b>
    escaped = re.sub(r"^#{1,6}\s*(.*?)$", r"<b>\1</b>", escaped, flags=re.MULTILINE)

    # 5. Restore allowed HTML tags
    escaped = escaped.replace("&lt;b&gt;", "<b>").replace("&lt;/b&gt;", "</b>")
    escaped = escaped.replace("&lt;font", "<font").replace("&lt;/font&gt;", "</font>")

    return escaped


def mask_candidate_name(name: str, index: int = 1) -> str:
    """Masks candidate full name to initials in Blind Hiring Mode."""
    if not name or not name.strip():
        return f"Candidate #{index}"
    parts = name.strip().split()
    initials = "".join([f"{p[0].upper()}." for p in parts if p])
    return f"Candidate #{index} ({initials})"


def generate_recruitment_report(
    jd: Optional[Dict[str, Any]] = None,
    shortlist: Optional[List[Dict[str, Any]]] = None,
    interview_questions: str = "",
    salary_data: str = "",
    candidates: Optional[List[Dict[str, Any]]] = None,
    evaluations: Optional[Dict[str, Any]] = None,
    scheduled_interviews: Optional[List[Dict[str, Any]]] = None,
    is_blind_mode: bool = False,
    session_title: Optional[str] = None,
    recruiter_name: Optional[str] = None,
) -> bytes:
    """
    Compiles Job Description, candidate stack-ranking, rubric evaluations,
    interview prep questions, salary expectations, and scheduled interviews
    into an executive-grade, corporate assessment ReportLab PDF document.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=45,
        bottomMargin=45,
    )

    styles = getSampleStyleSheet()

    # --- Typography & Styles ---
    brand_emerald = colors.HexColor("#059669")
    brand_navy = colors.HexColor("#0F172A")
    brand_slate = colors.HexColor("#334155")
    brand_muted = colors.HexColor("#64748B")
    border_color = colors.HexColor("#CBD5E1")
    light_bg = colors.HexColor("#F8FAFC")

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=brand_navy,
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=brand_muted,
    )

    section_title_style = ParagraphStyle(
        "SectionTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=brand_navy,
        spaceBefore=12,
        spaceAfter=5,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=brand_slate,
    )

    body_bold = ParagraphStyle(
        "BodyBold",
        parent=body_style,
        fontName="Helvetica-Bold",
        textColor=brand_navy,
    )

    bullet_style = ParagraphStyle(
        "Bullet",
        parent=body_style,
        leftIndent=14,
        firstLineIndent=-10,
        spaceAfter=3,
    )

    header_style = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.white,
    )

    kpi_number_style = ParagraphStyle(
        "KpiNum",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        alignment=1,  # Center
        textColor=brand_navy,
    )

    kpi_label_style = ParagraphStyle(
        "KpiLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.5,
        leading=10,
        alignment=1,  # Center
        textColor=brand_muted,
    )

    story = []

    # Safe data resolution
    jd_dict = jd or {}
    shortlist_list = shortlist or []
    all_candidates = candidates if (candidates and len(candidates) > 0) else shortlist_list
    evals_dict = evaluations or {}
    interviews_list = scheduled_interviews or []

    role_title = jd_dict.get("role") or "General Position"
    title_text = session_title or f"Hiring Campaign: {role_title}"
    recruiter = recruiter_name or "Lead Recruiter"
    now_str = datetime.now(timezone.utc).strftime("%B %d, %Y • %H:%M UTC")

    # =========================================================================
    # 1. Executive Banner & Header Block
    # =========================================================================
    badge_label = "Blind Mode (PII Masked)" if is_blind_mode else "Standard Mode (Candidate Details Unmasked)"
    badge_color = "#D97706" if is_blind_mode else "#059669"
    badge_bg = "#FFFBEB" if is_blind_mode else "#ECFDF5"

    banner_data = [
        [
            Paragraph(
                f"<font size='9' color='#059669'><b>RECRUITAI INTELLIGENT TALENT ENGINE</b></font><br/>"
                f"<b>{title_text}</b>",
                title_style,
            ),
            Paragraph(
                f"<div align='right'>"
                f"<font color='{badge_color}'><b>● {badge_label}</b></font><br/>"
                f"<font size='8' color='#64748B'>Target Role: <b>{role_title}</b></font><br/>"
                f"<font size='7.5' color='#94A3B8'>Generated: {now_str}</font><br/>"
                f"<font size='7.5' color='#94A3B8'>Audited By: {recruiter}</font>"
                f"</div>",
                subtitle_style,
            ),
        ]
    ]

    banner_table = Table(banner_data, colWidths=[340, 200])
    banner_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E2E8F0")),
            ("PADDING", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])
    )
    story.append(banner_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 2. Executive KPI Funnel Summary
    # =========================================================================
    total_pool_count = len(all_candidates)
    high_match_count = sum(1 for c in all_candidates if (c.get("match_score") or 0) >= 80)
    shortlisted_count = len(shortlist_list) or sum(
        1 for c in all_candidates if c.get("status") in ["shortlisted", "offered"]
    )
    scheduled_count = len(interviews_list)

    kpi_data = [
        [
            Paragraph(str(total_pool_count), kpi_number_style),
            Paragraph(str(high_match_count), kpi_number_style),
            Paragraph(f"<font color='#059669'>{shortlisted_count}</font>", kpi_number_style),
            Paragraph(f"<font color='#4F46E5'>{scheduled_count}</font>", kpi_number_style),
        ],
        [
            Paragraph("TALENT POOL", kpi_label_style),
            Paragraph("HIGH-FIT (&ge;80%)", kpi_label_style),
            Paragraph("SHORTLISTED", kpi_label_style),
            Paragraph("INTERVIEWS BOOKED", kpi_label_style),
        ],
    ]

    kpi_table = Table(kpi_data, colWidths=[135, 135, 135, 135])
    kpi_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
            ("BOX", (0, 0), (-1, -1), 0.5, border_color),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])
    )
    story.append(kpi_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 3. Position Calibration & Requirements Specification
    # =========================================================================
    story.append(Paragraph("1. Position Target & Rubric Calibration", section_title_style))

    exp_years = jd_dict.get("experience_years")
    exp_str = f"{exp_years}+ years" if exp_years is not None else "Not specified"
    tone_str = str(jd_dict.get("tone") or "Professional / Collaborative").capitalize()
    skills_list = jd_dict.get("required_skills") or []
    skills_str = ", ".join(skills_list) if skills_list else "General Competencies"
    summary_str = jd_dict.get("summary") or jd_dict.get("responsibilities") or "Production systems engineering and team delivery."
    if isinstance(summary_str, list):
        summary_str = "; ".join(summary_str[:3])

    jd_table_data = [
        [Paragraph("<b>Target Requisition:</b>", body_style), Paragraph(markdown_to_html(role_title), body_style)],
        [Paragraph("<b>Target Experience:</b>", body_style), Paragraph(markdown_to_html(exp_str), body_style)],
        [Paragraph("<b>Culture & Tone:</b>", body_style), Paragraph(markdown_to_html(tone_str), body_style)],
        [Paragraph("<b>Core Required Skills:</b>", body_style), Paragraph(markdown_to_html(skills_str), body_style)],
        [Paragraph("<b>Position Overview:</b>", body_style), Paragraph(markdown_to_html(str(summary_str)), body_style)],
    ]

    jd_table = Table(jd_table_data, colWidths=[130, 410])
    jd_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), light_bg),
            ("BOX", (0, 0), (-1, -1), 0.5, border_color),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
            ("PADDING", (0, 0), (-1, -1), 4.5),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ])
    )
    story.append(jd_table)
    story.append(Spacer(1, 12))

    # =========================================================================
    # 4. Candidate Stack-Ranking & Evaluation Matrix
    # =========================================================================
    story.append(Paragraph("2. Candidate Stack-Ranking & Assessment Matrix", section_title_style))

    # Combine and prioritize shortlisted first, then pool sorted by match score
    display_candidates = []
    seen_ids = set()

    for sc in shortlist_list:
        cid = sc.get("candidate_id") or sc.get("id") or sc.get("name")
        if cid not in seen_ids:
            seen_ids.add(cid)
            display_candidates.append(sc)

    for c in all_candidates:
        cid = c.get("candidate_id") or c.get("id") or c.get("name")
        if cid not in seen_ids:
            seen_ids.add(cid)
            display_candidates.append(c)

    # Sort descending by match score
    display_candidates.sort(key=lambda x: x.get("match_score") or 0, reverse=True)

    if display_candidates:
        # Table columns: Name (125), Fit Score (65), Status & Rubric (90), Matched Skills (130), Gaps & Notes (130) = 540
        matrix_data = [
            [
                Paragraph("Candidate Name", header_style),
                Paragraph("Match Score", header_style),
                Paragraph("Status & Rubric", header_style),
                Paragraph("Verified Competencies", header_style),
                Paragraph("Gaps & Recruiter Notes", header_style),
            ]
        ]

        for idx, cand in enumerate(display_candidates):
            raw_name = cand.get("name") or cand.get("full_name") or f"Candidate #{idx + 1}"
            display_name = mask_candidate_name(raw_name, idx + 1) if is_blind_mode else raw_name

            score_val = cand.get("match_score")
            score_num = int(score_val) if score_val is not None else 0
            score_color = "#059669" if score_num >= 80 else "#D97706" if score_num >= 50 else "#DC2626"
            score_text = f"<b><font color='{score_color}' size='10'>{score_num}%</font></b>"

            status_val = str(cand.get("status") or "new").capitalize()
            # Extract recruiter evaluations if present
            candidate_key = str(cand.get("candidate_id") or cand.get("id") or "")
            cand_eval: Dict[str, Any] = evals_dict.get(candidate_key, {}) if candidate_key else {}
            tech_s = cand_eval.get("tech_score") or cand.get("tech_score")
            comm_s = cand_eval.get("comm_score") or cand.get("comm_score")
            rubric_str = ""
            if tech_s is not None and comm_s is not None:
                rubric_str = f"<br/><font size='7' color='#475569'>Tech: {tech_s}/5 • Comm: {comm_s}/5</font>"

            matched_skills = cand.get("matched_skills") or cand.get("skills") or []
            if isinstance(matched_skills, list):
                matched_str = ", ".join(matched_skills[:5])
            else:
                matched_str = str(matched_skills)

            gaps = cand.get("gaps") or []
            if isinstance(gaps, list):
                gaps_str = ", ".join(gaps[:3]) if gaps else "No critical gaps identified"
            else:
                gaps_str = str(gaps)

            notes_str = cand_eval.get("notes") or cand.get("summary") or ""
            notes_line = f"<br/><font size='7' color='#64748B'><i>{notes_str[:120]}...</i></font>" if notes_str else ""

            matrix_data.append([
                Paragraph(f"<b>{markdown_to_html(display_name)}</b>", body_style),
                Paragraph(score_text, body_style),
                Paragraph(f"<b>{status_val}</b>{rubric_str}", body_style),
                Paragraph(markdown_to_html(matched_str), body_style),
                Paragraph(f"{markdown_to_html(gaps_str)}{notes_line}", body_style),
            ])

        matrix_table = Table(matrix_data, colWidths=[125, 65, 90, 130, 130])
        matrix_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), brand_navy),
                ("BOX", (0, 0), (-1, -1), 0.5, border_color),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
                ("PADDING", (0, 0), (-1, -1), 4.5),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, light_bg]),
            ])
        )
        story.append(matrix_table)
    else:
        story.append(Paragraph("No candidates currently ingested in this recruitment session.", body_style))

    story.append(Spacer(1, 12))

    # =========================================================================
    # 5. Technical & Gap-Probing Interview Guide
    # =========================================================================
    story.append(PageBreak())  # Clean break for interview section
    story.append(Paragraph("3. Technical & Gap-Probing Interview Questions", section_title_style))
    story.append(
        Paragraph(
            "Curated interview questions formulated by the LangGraph multi-agent supervisor "
            "to probe identified architecture gaps and benchmark hands-on competencies.",
            subtitle_style,
        )
    )
    story.append(Spacer(1, 6))

    if interview_questions and interview_questions.strip():
        q_lines = interview_questions.strip().split("\n")
        in_code_or_table = False
        for line in q_lines:
            raw_line = line.strip()
            if not raw_line:
                continue

            # Markdown header in questions
            if raw_line.startswith("#"):
                clean_header = re.sub(r"^#{1,6}\s*", "", raw_line)
                story.append(Spacer(1, 4))
                story.append(Paragraph(f"<b>{markdown_to_html(clean_header)}</b>", body_bold))
                story.append(Spacer(1, 2))
            elif raw_line.startswith(("-", "*")) or re.match(r"^\d+\.", raw_line):
                story.append(Paragraph(markdown_to_html(raw_line), bullet_style))
            else:
                story.append(Paragraph(markdown_to_html(raw_line), body_style))
                story.append(Spacer(1, 2))
    else:
        # Default high-impact structured rubric guide if none generated in chat
        default_qs = [
            f"<b>1. Architecture & System Design:</b> Explain the design of a scalable service relevant to <i>{role_title}</i>. What tradeoffs did you make between consistency, latency, and operational simplicity?",
            f"<b>2. Technical Competency Probe:</b> In your past production experience with <i>{skills_str}</i>, how did you diagnose and remediate a high-severity production failure or performance bottleneck?",
            "<b>3. Gap & Tradeoff Exploration:</b> Looking at areas where candidate competencies diverge from ideal role specifications, describe how you ramp up on unfamiliar domain frameworks within a tight delivery deadline.",
            "<b>4. Quality & Operational Readiness:</b> What automated testing strategies and observability practices do you mandate before shipping mission-critical features to end users?",
        ]
        for dq in default_qs:
            story.append(Paragraph(dq, bullet_style))
            story.append(Spacer(1, 3))

    story.append(Spacer(1, 10))

    # =========================================================================
    # 6. Market Salary & Compensation Benchmark
    # =========================================================================
    story.append(Paragraph("4. Target Compensation & Market Salary Benchmark", section_title_style))

    if salary_data and salary_data.strip():
        sal_clean = markdown_to_html(salary_data.strip()).replace("\n", "<br/>")
    else:
        sal_clean = (
            f"<b>Market Compensation Range for {role_title}:</b><br/>"
            f"• <b>Base Salary Target:</b> Competitive market median commensurate with {exp_str} experience.<br/>"
            f"• <b>Calibration Guidance:</b> Premium offers reserved for candidates exceeding 80% rubric match "
            f"with zero critical competency gaps in core stack ({skills_str})."
        )

    salary_table = Table([[Paragraph(sal_clean, body_style)]], colWidths=[540])
    salary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), light_bg),
            ("BOX", (0, 0), (-1, -1), 0.5, border_color),
            ("PADDING", (0, 0), (-1, -1), 7),
        ])
    )
    story.append(salary_table)
    story.append(Spacer(1, 10))

    # =========================================================================
    # 7. Scheduled Interviews & Coordination Log
    # =========================================================================
    story.append(Paragraph("5. Confirmed Interview Coordination Log", section_title_style))

    if interviews_list and len(interviews_list) > 0:
        sched_data = [
            [
                Paragraph("Candidate Name", header_style),
                Paragraph("Interview Slot / Schedule", header_style),
                Paragraph("Booking Timestamp", header_style),
                Paragraph("Status", header_style),
            ]
        ]
        for itv in interviews_list:
            cand_name = itv.get("candidate_name") or itv.get("candidate_id") or "Candidate"
            if is_blind_mode:
                cand_name = mask_candidate_name(cand_name)
            slot_str = itv.get("slot") or "TBD"
            booked_str = itv.get("booked_at") or "Confirmed"
            sched_data.append([
                Paragraph(f"<b>{markdown_to_html(cand_name)}</b>", body_style),
                Paragraph(markdown_to_html(slot_str), body_style),
                Paragraph(markdown_to_html(booked_str[:19]), body_style),
                Paragraph("<font color='#059669'><b>Confirmed</b></font>", body_style),
            ])

        sched_table = Table(sched_data, colWidths=[150, 180, 130, 80])
        sched_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), brand_navy),
                ("BOX", (0, 0), (-1, -1), 0.5, border_color),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
                ("PADDING", (0, 0), (-1, -1), 4.5),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, light_bg]),
            ])
        )
        story.append(sched_table)
    else:
        story.append(
            Paragraph(
                "No formal interview rounds currently booked. Shortlisted candidates are ready "
                "for calendar slot selection via the Workspace Scheduler.",
                body_style,
            )
        )

    story.append(Spacer(1, 14))

    # =========================================================================
    # 8. AI Governance, Fair Hiring & Compliance Disclaimer
    # =========================================================================
    story.append(HRFlowable(width="100%", thickness=0.5, color=border_color, spaceAfter=8))
    compliance_text = (
        "<b>AI Governance & Compliance Notice:</b> This dossier was generated by the RecruitAI "
        "autonomous multi-agent system. All evaluations, match scores, and gap analyses serve as decision "
        "support recommendations and have been reviewed by a designated human recruiter in full compliance "
        "with EEOC non-discrimination standards and GDPR Article 22 human-in-the-loop oversight mandates."
    )
    story.append(Paragraph(compliance_text, subtitle_style))

    # Build document with running header and footer canvas
    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
